import type { InferInsertModel } from "drizzle-orm";

import type { categories } from "./schema.js";

export const categoriesData: InferInsertModel<typeof categories>[] = [
	{
		id: "ones",
		label: "Enere",
		description: "Sum of all dice showing a 1",
		primitive: "sum_of_face",
		params: { face: 1 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "twos",
		label: "Toere",
		description: "Sum of all dice showing a 2",
		primitive: "sum_of_face",
		params: { face: 2 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "threes",
		label: "Treere",
		description: "Sum of all dice showing a 3",
		primitive: "sum_of_face",
		params: { face: 3 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "fours",
		label: "Firere",
		description: "Sum of all dice showing a 4",
		primitive: "sum_of_face",
		params: { face: 4 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "fives",
		label: "Femmere",
		description: "Sum of all dice showing a 5",
		primitive: "sum_of_face",
		params: { face: 5 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "sixes",
		label: "Seksere",
		description: "Sum of all dice showing a 6",
		primitive: "sum_of_face",
		params: { face: 6 },
		exampleDice: null,
		section: "upper",
	},
	{
		id: "one_pair",
		label: "1 Par",
		description: "Two dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 1, size: 2 },
		exampleDice: [1, 1],
		section: "lower",
	},
	{
		id: "two_pairs",
		label: "2 Par",
		description: "Two different pairs of dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 2, size: 2 },
		exampleDice: [1, 1, 2, 2],
		section: "lower",
	},
	{
		id: "three_pairs",
		label: "3 Par",
		description: "Three different pairs of dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 3, size: 2 },
		exampleDice: [1, 1, 2, 2, 3, 3],
		section: "lower",
	},
	{
		id: "four_pairs",
		label: "4 Par",
		description: "Four different pairs of dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 4, size: 2 },
		exampleDice: [1, 1, 2, 2, 3, 3, 4, 4],
		section: "lower",
	},
	{
		id: "five_pairs",
		label: "5 Par",
		description: "Five different pairs of dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 5, size: 2 },
		exampleDice: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
		section: "lower",
	},
	{
		id: "six_pairs",
		label: "6 Par",
		description: "Six different pairs of dice showing the same face",
		primitive: "n_groups_of_size",
		params: { groups: 6, size: 2 },
		exampleDice: [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6],
		section: "lower",
	},
	{
		id: "three_of_a_kind",
		label: "3 Ens",
		description: "Three dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 3 },
		exampleDice: [6, 6, 6],
		section: "lower",
	},
	{
		id: "four_of_a_kind",
		label: "4 Ens",
		description: "Four dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 4 },
		exampleDice: [6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "five_of_a_kind",
		label: "5 Ens",
		description: "Five dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 5 },
		exampleDice: [6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "six_of_a_kind",
		label: "6 Ens",
		description: "Six dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 6 },
		exampleDice: [6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "seven_of_a_kind",
		label: "7 Ens",
		description: "Seven dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 7 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "eight_of_a_kind",
		label: "8 Ens",
		description: "Eight dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 8 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "nine_of_a_kind",
		label: "9 Ens",
		description: "Nine dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 9 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "ten_of_a_kind",
		label: "10 Ens",
		description: "Ten dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 10 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "eleven_of_a_kind",
		label: "11 Ens",
		description: "Eleven dice showing the same face",
		primitive: "n_of_a_kind_sum",
		params: { requiredCount: 11 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "two_by_three",
		label: "2x3 Ens",
		description:
			"Two separate groups of three dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 2, size: 3 },
		exampleDice: [5, 5, 5, 6, 6, 6],
		section: "lower",
	},
	{
		id: "two_by_four",
		label: "2x4 Ens",
		description:
			"Two separate groups of four dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 2, size: 4 },
		exampleDice: [5, 5, 5, 5, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "two_by_five",
		label: "2x5 Ens",
		description:
			"Two separate groups of five dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 2, size: 5 },
		exampleDice: [5, 5, 5, 5, 5, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "two_by_six",
		label: "2x6 Ens",
		description:
			"Two separate groups of six dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 2, size: 6 },
		exampleDice: [5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "three_by_three",
		label: "3x3 Ens",
		description:
			"Three separate groups of three dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 3, size: 3 },
		exampleDice: [4, 4, 4, 5, 5, 5, 6, 6, 6],
		section: "lower",
	},
	{
		id: "three_by_four",
		label: "3x4 Ens",
		description:
			"Three separate groups of four dice, each showing a different face",
		primitive: "n_groups_of_size",
		params: { groups: 3, size: 4 },
		exampleDice: [4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "low_straight",
		label: "Lille Straight",
		description: "A sequence of 1-2-3-4-5",
		primitive: "straight",
		params: { straightLow: 1, straightHigh: 5, fixedScore: 15 },
		exampleDice: [1, 2, 3, 4, 5],
		section: "lower",
	},
	{
		id: "high_straight",
		label: "Stor Straight",
		description: "A sequence of 2-3-4-5-6",
		primitive: "straight",
		params: { straightLow: 2, straightHigh: 6, fixedScore: 20 },
		exampleDice: [2, 3, 4, 5, 6],
		section: "lower",
	},
	{
		id: "royal_straight",
		label: "Royal Straight",
		description: "A sequence of 1-2-3-4-5-6",
		primitive: "straight",
		params: { straightLow: 1, straightHigh: 6, fixedScore: 30 },
		exampleDice: [1, 2, 3, 4, 5, 6],
		section: "lower",
	},
	{
		id: "lille_claus",
		label: "Lille Claus",
		description: "A sequence of 1-2-3-4-5-6 with 2 extra sixes",
		primitive: "straight_plus_extra",
		params: {
			straightLow: 1,
			straightHigh: 6,
			extraFace: 6,
			extraCount: 2,
			fixedScore: 50,
		},
		exampleDice: [1, 2, 3, 4, 5, 6, 6, 6],
		section: "lower",
	},
	{
		id: "store_claus",
		label: "Store Claus",
		description: "A sequence of 1-2-3-4-5-6 with 3 extra sixes",
		primitive: "straight_plus_extra",
		params: {
			straightLow: 1,
			straightHigh: 6,
			extraFace: 6,
			extraCount: 3,
			fixedScore: 75,
		},
		exampleDice: [1, 2, 3, 4, 5, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "knold",
		label: "Knold",
		description: "A sequence of 1-2-3-4-5-6 with 4 extra sixes",
		primitive: "straight_plus_extra",
		params: {
			straightLow: 1,
			straightHigh: 6,
			extraFace: 6,
			extraCount: 4,
			fixedScore: 100,
		},
		exampleDice: [1, 2, 3, 4, 5, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "tot",
		label: "Tot",
		description: "A sequence of 1-2-3-4-5-6 with 5 extra sixes",
		primitive: "straight_plus_extra",
		params: {
			straightLow: 1,
			straightHigh: 6,
			extraFace: 6,
			extraCount: 5,
			fixedScore: 150,
		},
		exampleDice: [1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "kaptajn_vom",
		label: "Kaptajn Vom",
		description: "A sequence of 1-2-3-4-5-6 with 6 extra sixes",
		primitive: "straight_plus_extra",
		params: {
			straightLow: 1,
			straightHigh: 6,
			extraFace: 6,
			extraCount: 6,
			fixedScore: 200,
		},
		exampleDice: [1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "house", // Also known as "Lillemor" in Gigant-Yatzy
		label: "Hus",
		description: "Three of a kind and a pair",
		primitive: "two_groups_sizes",
		params: { sizeA: 3, sizeB: 2 },
		exampleDice: [6, 6, 6, 5, 5],
		section: "lower",
	},
	{
		id: "poeten",
		label: "Poeten",
		description: "Four of a kind and a pair",
		primitive: "two_groups_sizes",
		params: { sizeA: 4, sizeB: 2 },
		exampleDice: [6, 6, 6, 6, 5, 5],
		section: "lower",
	},
	{
		id: "momsemor",
		label: "Momsemor",
		description: "Five of a kind and a pair",
		primitive: "two_groups_sizes",
		params: { sizeA: 5, sizeB: 2 },
		exampleDice: [6, 6, 6, 6, 6, 5, 5],
		section: "lower",
	},
	{
		id: "skipperskraek",
		label: "Skipperskræk",
		description: "Six of a kind and a pair",
		primitive: "two_groups_sizes",
		params: { sizeA: 6, sizeB: 2 },
		exampleDice: [6, 6, 6, 6, 6, 6, 5, 5],
		section: "lower",
	},
	{
		id: "radiserne",
		label: "Radiserne",
		description: "Four of a kind and three of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 4, sizeB: 3 },
		exampleDice: [6, 6, 6, 6, 5, 5, 5],
		section: "lower",
	},
	{
		id: "basserne",
		label: "Basserne",
		description: "Five of a kind and three of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 5, sizeB: 3 },
		exampleDice: [6, 6, 6, 6, 6, 5, 5, 5],
		section: "lower",
	},
	{
		id: "gyldenspjaet",
		label: "Gyldenspjæt",
		description: "Six of a kind and three of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 6, sizeB: 3 },
		exampleDice: [6, 6, 6, 6, 6, 6, 5, 5, 5],
		section: "lower",
	},
	{
		id: "kasket_karl",
		label: "Kasket Karl",
		description: "Five of a kind and four of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 5, sizeB: 4 },
		exampleDice: [6, 6, 6, 6, 6, 5, 5, 5, 5],
		section: "lower",
	},
	{
		id: "klaus_kludder",
		label: "Klaus Kludder",
		description: "Six of a kind and four of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 6, sizeB: 4 },
		exampleDice: [6, 6, 6, 6, 6, 6, 5, 5, 5, 5],
		section: "lower",
	},
	{
		id: "jens_lyn",
		label: "Jens Lyn",
		description: "Six of a kind and five of a kind",
		primitive: "two_groups_sizes",
		params: { sizeA: 6, sizeB: 5 },
		exampleDice: [6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5],
		section: "lower",
	},
	{
		id: "chance",
		label: "Chance",
		description: "Sum of all dice",
		primitive: "chance",
		params: {},
		exampleDice: null,
		section: "lower",
	},
	{
		id: "yatzy_5",
		label: "Yatzy",
		description: "All 5 dice showing the same face",
		primitive: "yatzy",
		params: { flatBonus: 50, includeEyesBonus: false, requiredCount: 5 },
		exampleDice: [6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "yatzy_6",
		label: "Yatzy",
		description: "All 6 dice showing the same face",
		primitive: "yatzy",
		params: { flatBonus: 50, includeEyesBonus: true, requiredCount: 6 },
		exampleDice: [6, 6, 6, 6, 6, 6],
		section: "lower",
	},
	{
		id: "yatzy_12",
		label: "Yatzy",
		description: "All 12 dice showing the same face",
		primitive: "yatzy",
		params: { flatBonus: 250, includeEyesBonus: true, requiredCount: 12 },
		exampleDice: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
		section: "lower",
	},
];
